[project]
name = "studio-funzioni"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "sympy>=1.14.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
